apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: recipe-rush
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJzdW4xMjEzIiwicGFzc3dvcmQiOiJncTU3MzMwNTA1ISIsImVtYWlsIjoiZ3FwYXJrMUBuYXZlci5jb20iLCJhdXRoIjoiYzNWdU1USXhNenBuY1RVM016TXdOVEExSVE9PSJ9fX0=
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: recipe-rush
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cXdlcjEyMzQ=